### ISSUE TITLE
An error occurred in generate datasets

### ISSUE THREAD

**Issue by XaryWorld** [FlyHighest/UnrealPerson#15]
After executing ce Add_Actor, executing the vget /camera/1/object_mask png command will show that the characters added later will not appear in the mask image
![c001_6_lit](https://user-images.githubusercontent.com/108608122/236405862-5d408097-ea30-4713-bfd4-aa05ce8df2c6.png)
![c001_6_mask](https://user-images.githubusercontent.com/108608122/236405897-1975a710-782a-407b-bdc5-11dcd19c89f8.png)

**Comment by tyz1994** [comment]
I remember that unrealcv will assign colors to each object in the scene first. Maybe it is due to this MH object is not registered in unrealcv. Perhaps you can try running this method first:

https://github.com/FlyHighest/UnrealPerson/blob/9fd5a882bea16f6289f0353b78140bff36c16609/UnrealPerson-DataSynthesisToolkit/generate_datasets.py#L157

**Comment by XaryWorld** [comment]
The problem is not solved.

Start with datautils.get_object_color()

There is no MH object in the scene.

Don't you need to do ce Add_Actor first to add the actor

**Comment by tyz1994** [comment]
Surely you have to add_actor first. See line 155-157 in generate_datasets.py.

**Comment by XaryWorld** [comment]
Sorry, I misunderstood your meaning.

Using datautils.get_object_color(), we can get the color allocation information of related actors.

Actor is not shown in the mask picture

**Comment by tyz1994** [comment]
Are the lit and object_mask images obtained at the same time? If the man walk too fast, it could walk out of camera view when getting object_mask. 
Or, perhaps it is an unrealcv/ue4 issue. I have modified unrealcv to use it in a specific version of ue4. If you are not using exactly the same UE version, some errors can happen. 

It's been a long time since the last time I used UE4 synthesis toolkit. I don't have an environment now.

**Comment by XaryWorld** [comment]
Thank you for your reply. I created the image after the pause, probably not the reason why the pedestrian is walking too fast.
And I used ue4.27 version, so I did not use your ue4.24 version of unrealcv. Maybe there is something wrong with the unrealcv plug-in.
